### PR TITLE
Manual entry value change event added & a sample project

### PR DESCRIPTION
**Pull request by zainniazi**
This pull request contains
- Manual entry value change event, previously there was no way to get that change
- A sample project
- Angular 7 support along with Mouse Delta support to latest
- Structure change

### CODE REVIEW

**Comment by zainniazi** [comment]
@wajdibeltaifa Can you please help with this ?
We are using this in our project.

**Comment by zainniazi** [comment]
Hey @wajdibeltaifa,

Thanks for the response. 
According to your recommendation i looked into the documentation [here](https://angular.io/guide/creating-libraries) and couple of other libraries which i'm already contributing on, they are following the latest pattern i guess.

Let's have a look here
https://github.com/Napster2210/ngx-spinner 

Here is my suggestion let's keep the structure and delete the sample project if you like that, and people such as myself they can add a sample/test project for testing and then delete that easily.

Thanks, do let me know what you think.

I'll also update the pull request.

**Comment by zainniazi** [comment]
@wajdibeltaifa please see this
https://github.com/wajdibeltaifa/ng-number-picker/pull/3/commits/d3c97b54e5cc6df6587a5438e00d894ea7e90737

**Comment by wajdibeltaifa** [comment]
@zainniazi It looks good, thks for your contributing.

**Pull request merged**
